import asyncio
import os
from playwright.async_api import async_playwright
from datetime import datetime

async def post_to_tsvideo(news_data: dict, app_url: str = "http://localhost/tsvideo", username: str = "admin", password: str = "password"):
    """
    Automates the TSVideo dashboard to post a news card to Facebook.
    news_data should contain:
    - headline: str
    - content: str
    - category: str
    - image_path: str (absolute path to the downloaded image)
    """
    async with async_playwright() as p:
        # Launch Chromium (headless by default, set headless=False for debugging)
        browser = await p.chromium.launch(headless=True, args=['--no-sandbox', '--disable-dev-shm-usage'])
        context = await browser.new_context(viewport={'width': 1280, 'height': 800})
        page = await context.new_page()

        try:
            # 1. Navigate to TSVideo Login (or Dashboard directly if no login needed locally)
            await page.goto(f"{app_url}/index.php")
            
            # Check if login is required (if we see the username field)
            if await page.locator("input[name='username']").count() > 0:
                await page.fill("input[name='username']", username)
                await page.fill("input[name='password']", password)
                await page.click("button[type='submit']")
                await page.wait_for_url(f"{app_url}/dashboard.php", timeout=10000)
            
            # Wait for dashboard to load
            await page.wait_for_selector("#input-h1")

            # 2. Inject Data
            # Fill Headline
            await page.fill("#input-h1", news_data.get("headline", ""))
            
            # Select Category
            category = news_data.get("category", "Local News")
            # If the exact category isn't in the list, default to first or handle it
            try:
                await page.select_option("#news-category", category)
            except Exception:
                pass # ignore if category doesn't exist in dropdown

            # Upload Image
            image_path = news_data.get("image_path")
            if image_path and os.path.exists(image_path):
                # Unhide the file input if needed (Playwright can set files on hidden inputs directly usually)
                await page.set_input_files("#manual-img-upload", image_path)
            
            # Give the UI a moment to update the canvas
            await page.wait_for_timeout(2000)

            # 3. Post to Facebook
            # Ensure "Media Type: Image" is selected
            await page.select_option("#fb-media-type", "image")
            
            # Fill content into bulk-headline (or whatever is used for FB caption)
            fb_caption = f"{news_data.get('headline')}\n\n{news_data.get('content')}"
            await page.fill("#bulk-headline", fb_caption)
            
            # Click "Post Now" (fb-post-single-btn)
            await page.click("#fb-post-single-btn")
            
            # Wait for 10 seconds to allow the post to finish (in real app, wait for success toast)
            await page.wait_for_timeout(10000)
            
            return {"status": "success", "message": "Posted to Facebook successfully via TSVideo"}
            
        except Exception as e:
            return {"status": "error", "message": str(e)}
        finally:
            await browser.close()

# For local testing
if __name__ == "__main__":
    test_data = {
        "headline": "Test Automated Headline",
        "content": "This is a test content generated by SAM AI Automation.",
        "category": "World News",
        "image_path": "" # Put a valid local path here if testing
    }
    result = asyncio.run(post_to_tsvideo(test_data))
    print(result)
